services:
  redis:
      image: redis/redis-stack:latest
      container_name: redis
      ports:
        - "6379:6379"
        - "8002:8001"
      restart: unless-stopped
      healthcheck:
        test: ['CMD', 'redis-cli', 'ping']
        interval: 30s
        timeout: 10s
        retries: 10


  batch_indexer:
    build:
      context: ./batch_indexer
      dockerfile: Dockerfile

    container_name: batch_indexer

    ports:
      - "8001:8001"

    env_file:
      - .env

    volumes:
      - ./artifacts/faiss:/app/artifacts/faiss

    environment:
      - FAISS_LOCAL_DIR=/app/artifacts/faiss

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/docs"]
      interval: 30s
      timeout: 3s
      retries: 80
      start_period: 600s



  rag_api:
    build:
      context: ./rag_api
      dockerfile: Dockerfile

    container_name: rag_api

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - ./artifacts/faiss:/app/artifacts/faiss

    environment:
      - FAISS_LOCAL_DIR=/app/artifacts/faiss
      - REDIS_URL=//redis:6379

    depends_on:
      redis:
        condition: service_healthy
      batch_indexer:
        condition: service_healthy

    restart: unless-stopped
